In [5]:
import numpy as np

In [8]:
#Задача No.1

print("Введите размер матрицы через пробел\n")

n, x = map(int, input().split())

vec = np.zeros(n)
vec[x] = 1

vec

Введите размер матрицы через пробел

7 2


array([0., 0., 1., 0., 0., 0., 0.])

In [3]:
#Задача No.2

print("Введите три числа через пробел")

n, m, s = map(int, input().split())

vec = np.arange(n, m, s)
vec

Введите три числа через пробел
0 20 2


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
#Задача No.3

np.random.randint(low = 0, high = 8, size = (3,3))

array([[4, 6, 1],
       [7, 7, 6],
       [6, 2, 7]])

In [12]:
#Задача No.4

np.random.seed(seed = 10)
mat = np.random.rand(4, 4)

print(f'max {np.max(mat[0, :]).round(4)}')
print(f'min {np.min(mat[1, :]).round(4)}')
print(f'mean {np.mean(mat[2, :]).round(4)}')
print(f'sum {np.sum(mat[3, :]).round(4)}')

max 0.7713
min 0.1981
mean 0.4741
sum 1.9413


In [13]:
#Задача No.5

np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
#Задача No.6

mat = np.random.rand(6, 6, 6)
print("Max No.: " + str(np.max(mat).round(4)))

Max No.: 0.9876


In [15]:
#Задача No.7

def cond_and_mult_and_trans(A, B):
    if A.shape[1] == B.shape[0]:
        return np.transpose(A @ B)
    
    return "Невозможно перемножать"

A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2, 3], [3, 4, 5], [2, 2, 3]])

cond_and_mult_and_trans(A, B)

'Невозможно перемножать'

In [16]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2], [3, 4]])

cond_and_mult_and_trans(A, B)

array([[ 7, 15],
       [10, 22]])

In [17]:
#Задача No.8

def func(x, y):
    return x * x + 2.0 * y * y + np.exp (x + y)

def f_x(func, x, y, eps = 0.001):
    return (func(x + eps, y) - func(x, y)) / eps

def f_y(func, x, y, eps = 0.001):
    return (func(x, y + eps) - func(x, y)) / eps

EPS = 0.001
INIT = np.array([1.0, -1.75])
LEARN_RATE = 0.05
ITER = 10000

X_prev = INIT
delta = 1
for i in range(ITER):
    if delta > EPS:
        fxx = f_x(func, X_prev[0], X_prev[1], eps=0.001)
        fyy = f_y(func, X_prev[0], X_prev[1], eps=0.001)
        grad = np.array([fxx, fyy])
        
        X_next = X_prev - LEARN_RATE * grad
        
        delta = np.sqrt(np.sum(grad * grad))
        
        X_prev = X_next
        
    else:
        break

print(f"Значение функции {func(X_next[0], X_next[1]).round(4)}")
print(f"x_min {X_next[0].round(4)}")
print(f"y_min {X_next[1].round(4)}")
print(f"Производная в x_min {f_x(func, X_next[0], X_next[1], eps=0.001).round(4)}")
print(f"Производная в y_min {f_y(func, X_next[0], X_next[1], eps=0.001).round(4)}")
print(f"Градиент {np.sqrt((grad**2).sum()).round(9)}")

Значение функции 0.7723
x_min -0.3128
y_min -0.1569
Производная в x_min 0.0008
Производная в y_min -0.0002
Градиент 0.000963264
